version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pwa_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pwa_backend
      MYSQL_USER: xxgjj
      MYSQL_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: pwa_redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    command: redis-server --requirepass "1234567890" --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "1234567890", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5