AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    MemorySize: 256
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        DB_HOST: "18.139.162.43"
        DB_PORT: "3306"
        DB_USER: "xxgjj"
        DB_PASSWORD: "123456"
        DB_NAME: "pwa_backend"
        REDIS_HOST: "18.139.162.43"
        REDIS_PORT: "6379"
        REDIS_PASSWORD: "1234567890"
        CORS_ORIGIN: "*"

Resources:
  PwaApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"

  PwaBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: ./
      Timeout: 30
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref PwaApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Sub https://${PwaApi}.execute-api.${AWS::Region}.amazonaws.com